
project_id = "oncsaunsqtekwwbzvvyh"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:5173"

[realtime]
enabled = true

[[functions]]
name = "create-payment"
verify_jwt = true

[[functions]]
name = "create-paypal-payment"
verify_jwt = true

[[functions]]
name = "create-shipment"
verify_jwt = true

[[functions]]
name = "email-receipt"
verify_jwt = true

[[functions]]
name = "enable-mfa"
verify_jwt = true

[[functions]]
name = "generate-mfa-secret"
verify_jwt = true

[[functions]]
name = "get-collection-schedules"
verify_jwt = true

[[functions]]
name = "send-announcement-notification"
verify_jwt = true

[[functions]]
name = "send-brevo-email"
verify_jwt = true

[[functions]]
name = "send-email"
verify_jwt = true

[[functions]]
name = "send-quote-email"
verify_jwt = true

[[functions]]
name = "send-support-notification"
verify_jwt = true

[[functions]]
name = "verify-mfa-code"
verify_jwt = true

[[functions]]
name = "verify-mfa-login"
verify_jwt = true

[[functions]]
name = "verify-payment"
verify_jwt = true
